name: Firebase Test Lab

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Code Signing
      env:
        APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
        PROVISIONING_PROFILE_1: ${{ secrets.PROVISIONING_PROFILE_1 }}
        PROVISIONING_PROFILE_2: ${{ secrets.PROVISIONING_PROFILE_2 }}
        PROVISIONING_PROFILE_3: ${{ secrets.PROVISIONING_PROFILE_3 }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      run: |
        echo "$APPLE_CERTIFICATE" | base64 --decode > ./certificate.p12
        echo "$PROVISIONING_PROFILE_1" | base64 --decode > ./profile1.mobileprovision
        echo "$PROVISIONING_PROFILE_2" | base64 --decode > ./profile2.mobileprovision
        echo "$PROVISIONING_PROFILE_3" | base64 --decode > ./profile3.mobileprovision
        security create-keychain -p "" build.keychain
        security import ./certificate.p12 -t agg -k ~/Library/Keychains/build.keychain -P "$CERTIFICATE_PASSWORD" -A
        security list-keychains -s ~/Library/Keychains/build.keychain
        security default-keychain -s ~/Library/Keychains/build.keychain
        security unlock-keychain -p "" ~/Library/Keychains/build.keychain
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp ./profile1.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        cp ./profile2.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        cp ./profile3.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/


    - name: Prepare Test Build
      env:
        DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
        CODE_SIGN_IDENTITY: ${{ secrets.CODE_SIGN_IDENTITY }}
        #PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}s
      run: |
        chmod +x prepareTestBuild-rdc.sh
        ./prepareTestBuild-rdc.sh

    - name: Decode GCP Service Account Key
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > $HOME/gcp-service-account-key.json

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
        service_account_key_file: $HOME/gcp-service-account-key.json
        export_default_credentials: true
    
    - name: Run Tests on Firebase Test Lab
      run: |
        gcloud firebase test ios run --test AppsToTest-rdc/FirebaseDemoTests.zip \
        --device model=iphone11pro,version=16.6,locale=en_US,orientation=portrait \
        --device model=iphone14pro,version=16.6,locale=en_US,orientation=portrait
