name: Firebase Test Lab

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare Test Build
      env:
        DEVELOPMENT_TEAM_ID: ${{ secrets.DEVELOPMENT_TEAM }}
      run: |
        chmod +x prepareTestBuild-rdc.sh
        ./prepareTestBuild-rdc.sh

    - name: Decode GCP Service Account Key
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > $HOME/gcp-service-account-key.json

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
        service_account_key_file: $HOME/gcp-service-account-key.json
        export_default_credentials: true
    
    - name: Run Tests on Firebase Test Lab
      run: |
        gcloud firebase test ios run --test AppsToTest-rdc/FirebaseDemoTests.zip \
        --device model=iphone11pro,version=16.6,locale=en_US,orientation=portrait \
        --device model=iphone14pro,version=16.6,locale=en_US,orientation=portrait
